In [1]:
#ML Final Project Kaggle Competition
#By Jeremiah Pratt and Joseph Bentivegna
#Dedicated to my mother, who would yell at me for not picking my clothes up off
#of my own bedroom floor.

In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn.preprocessing import PolynomialFeatures

In [3]:
trainyBoi = pd.read_csv('train.csv',header=None)
testyBoi = pd.read_csv('test.csv',header=None)

In [4]:
scaler = MinMaxScaler()
poly = PolynomialFeatures(2)
X = trainyBoi.iloc[:,1:]
X = scaler.fit_transform(X)
X = poly.fit_transform(X)
Y = trainyBoi.iloc[:,0]
kf = KFold(n_splits=3, shuffle=True)
knn = KNeighborsClassifier(algorithm='auto')
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    knn.fit(X_train,Y_train)
    print(knn.score(X_test,Y_test))
print(metrics.confusion_matrix(Y_test,knn.predict(X_test)))

0.553892215569
0.600600600601
0.51951951952
[[11  1  1  2  4  1  5  2  1  3]
 [ 4 13  0  3  1  3  3  0  1  0]
 [ 6  0 19  0  5  0  5  3  2  2]
 [ 3  1  0 23  0  0  7  0  1  0]
 [ 9  0  4  0 16  0  3  0  0  1]
 [ 0  0  0  3  0 21  0  0  1  0]
 [ 4  0  0  2  0  0 28  0  0  0]
 [ 6  2  1  0  1  0  1 20  2  4]
 [13  1  6  1  0  0  2  0  9  3]
 [ 4  4  0  1  1  0  6  4  0 13]]
