In [1]:
#ML Final Project Kaggle Competition
#By Jeremiah Pratt and Joseph Bentivegna
#Dedicated to my mother, who always withheld affection and told me I'd never make anything of myself.

In [87]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics

In [61]:
trainyBoi = pd.read_csv('train.csv',header=None)
testyBoi = pd.read_csv('test.csv',header=None)

In [106]:
scaler = MinMaxScaler()
X = trainyBoi.iloc[:,1:]
X = scaler.fit_transform(X)
Y = trainyBoi.iloc[:,0]
kf = KFold(n_splits=5, shuffle=True)
logreg = linear_model.LogisticRegression(penalty='l2',C=1,solver='newton-cg',max_iter=1000)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    logreg.fit(X_train,Y_train)
    print(logreg.score(X_test,Y_test))
print(metrics.confusion_matrix(Y_test,logreg.predict(X_test)))

0.6
0.605
0.645
0.545
0.645
[[ 8  0  0  0  3  0  1  0  0  2]
 [ 0 19  0  0  3  1  0  0  0  1]
 [ 0  0  9  1  2  1  0  0  5  0]
 [ 0  1  1 18  1  2  1  0  2  0]
 [ 2  0  2  0 17  1  0  0  1  1]
 [ 0  0  1  0  0 13  0  0  0  1]
 [ 0  0  0  1  0  1 11  0  0  1]
 [ 1  0  1  1  0  0  1 14  1  2]
 [ 5  1  4  0  0  0  1  0  5  1]
 [ 1  0  1  3  0  1  2  3  1 15]]
