In [1]:
#ML Final Project Kaggle Competition
#By Jeremiah Pratt and Joseph Bentivegna
#Dedicated to my mother, who always withheld affection and told me I'd never make anything of myself.

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import svm
from sklearn import gaussian_process
from sklearn.model_selection import KFold
from sklearn.feature_selection import VarianceThreshold
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import robust_scale
from sklearn.preprocessing import PolynomialFeatures

In [3]:
trainyBoi = pd.read_csv('train.csv',header=None)
testyBoi = pd.read_csv('test.csv',header=None)

In [8]:
#Logistic Regression
scaler = MinMaxScaler()
X = trainyBoi.iloc[:,1:]
X = scaler.fit_transform(X)
Y = trainyBoi.iloc[:,0]
kf = KFold(n_splits=5, shuffle=True)
logreg = linear_model.LogisticRegression(penalty='l2',C=1,solver='newton-cg',max_iter=1000)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    logreg.fit(X_train,Y_train)
    print(logreg.score(X_test,Y_test))
#print(metrics.confusion_matrix(Y_test,logreg.predict(X_test)))

logreg.fit(X,Y)
pred = pd.DataFrame(logreg.predict(testyBoi))
pred.to_csv('results.csv',index_label=['Id','Prediction'],index=list(range(1,200)))

#Playing with feature selection, doesn't really make it better
sel = VarianceThreshold(threshold=(.9*(1-.9)))
sel.fit_transform(X)
logreg = linear_model.LogisticRegression(penalty='l2',C=1,solver='newton-cg',max_iter=1000)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    logreg.fit(X_train,Y_train)
    print(logreg.score(X_test,Y_test))


0.67
0.615
0.59
0.565
0.605
0.56
0.56
0.63
0.645
0.665


In [218]:
#Tried Stochastic Gradient Descent
scaler = MinMaxScaler(feature_range=(0,1))
X = trainyBoi.iloc[:,1:]
X = scaler.fit_transform(X)
Y = trainyBoi.iloc[:,0]
kf = KFold(n_splits=2, shuffle=True)
SGD = linear_model.SGDClassifier(loss="log",penalty="l2",tol=1e-3,max_iter=1000)
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    SGD.fit(X_train,Y_train)
    print(SGD.score(X_test,Y_test))
print(metrics.confusion_matrix(Y_test,SGD.predict(X_test)))
SGD.fit(X,Y)

0.566
0.472
[[ 4 34  1  5  1  0  2  5  3  1]
 [ 1 39  0  1  2  0  0  1  1  1]
 [ 0 19  7  3  7  1  0  6  7  1]
 [ 0 12  0 28  0  0  1  4  0  1]
 [ 1 15  0  3 20  0  0  5  3  1]
 [ 0 20  0  1  0 37  0  0  0  0]
 [ 0 11  0  2  0  0 33  1  0  3]
 [ 0  8  0  0  0  0  0 34  0  2]
 [ 0 24  0  1  4  1  0  5  7  3]
 [ 0 16  0  1  1  1  0  9  1 27]]


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=1000, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=0.001, verbose=0, warm_start=False)