In [1]:
#ML Final Project Kaggle Competition
#By Jeremiah Pratt and Joseph Bentivegna
#Dedicated to my mother, who wouldn't hurt a fly but instead would get my father
#to kill it.

In [2]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn.preprocessing import PolynomialFeatures

In [3]:
trainyBoi = pd.read_csv('train.csv',header=None)
testyBoi = pd.read_csv('test.csv',header=None)

In [23]:
scaler = MinMaxScaler()
#poly = PolynomialFeatures(2)
X = trainyBoi.iloc[:,1:]
X = scaler.fit_transform(X)
#X = poly.fit_transform(X)
Y = trainyBoi.iloc[:,0]
kf = KFold(n_splits=3, shuffle=True)
clf = svm.SVC(C=5, decision_function_shape='ovr')
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    clf.fit(X_train,Y_train)
    print(clf.score(X_test,Y_test))
print(metrics.confusion_matrix(Y_test,clf.predict(X_test)))

clf.fit(X,Y)
testyBoi = scaler.fit_transform(testyBoi)
predictions = clf.predict(testyBoi)
pred = pd.DataFrame(predictions)
pred.to_csv('output.csv')

0.604790419162
0.618618618619
0.582582582583
[[13  0  1  0  9  1  4  0  8  1]
 [ 2 18  0  1  1  2  3  0  2  2]
 [ 3  0 16  1  5  1  0  1  5  3]
 [ 1  1  0 20  1  0  2  2  1  0]
 [ 5  0  6  0 21  0  0  0  1  0]
 [ 1  2  0  3  0 28  0  0  0  0]
 [ 7  0  1  2  0  0 26  0  0  1]
 [ 2  0  1  0  1  0  0 19  2  5]
 [ 8  0  7  1  2  1  0  0 10  4]
 [ 1  1  1  0  1  1  2  3  2 23]]
